/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pjgt4y4ys5aqvnytwzf3ne7ake.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:9b2c0b07-931a-4985-9f40-03a2919655b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Clo0WrOuq",
    "aws_user_pools_web_client_id": "57o5hpf9b01mdngmf4rir2l4u3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "icegainzofficialproductimages113312-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
